version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: try1234
      MYSQL_DATABASE: yoriview
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-ptry1234",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  backend:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY_BACKEND}:${IMAGE_TAG}
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/yoriview?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=try1234
      - JWT_SECRET=your_production_jwt_secret_key_key_key_key
      # OCR 관련 환경변수
      - CLOVA_OCR_SECRET_KEY=${CLOVA_OCR_SECRET_KEY}
      - CLOVA_OCR_APIGW_INVOKE_URL=${CLOVA_OCR_APIGW_INVOKE_URL}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY_FRONTEND}:${IMAGE_TAG}
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mysql_data:
